# Generated by Django 4.2.29 on 2026-08-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeps', '0001_aeps_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aepsproviderconfig',
            name='environment',
            field=models.CharField(choices=[('uat', 'UAT'), ('prod', 'Production')], db_index=True, default='prod', max_length=10),
        ),
    ]
