# Generated by Django 4.2.30 on 2026-08-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeps', '0005_merchant_scanner_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aepsproviderconfig',
            name='egress_ip',
            field=models.CharField(blank=True, default='', help_text="Optional override for the public egress IP sent as ipAddress. Leave blank to auto-detect this host's outbound address.", max_length=64),
        ),
    ]
