# Generated by Django 4.2.30 on 2026-08-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeps', '0006_alter_aepsproviderconfig_egress_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='aepsproviderconfig',
            name='capture_ftype_aeps',
            field=models.CharField(choices=[('0', '0 — FMR'), ('1', '1 — FIR'), ('2', '2 — Full image')], default='0', help_text='fType requested for 2FA and AEPS product captures', max_length=1),
        ),
        migrations.AddField(
            model_name='aepsproviderconfig',
            name='capture_ftype_ekyc',
            field=models.CharField(choices=[('0', '0 — FMR'), ('1', '1 — FIR'), ('2', '2 — Full image')], default='2', help_text='fType requested for eKYC captures', max_length=1),
        ),
    ]
