# Generated by Django 4.2.30 on 2026-08-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeps', '0007_aepsproviderconfig_capture_ftype_aeps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aepsproviderconfig',
            name='egress_ip',
            field=models.CharField(blank=True, default='', help_text='Override for the public egress IP sent as ipAddress. Normally leave blank — it is auto-detected. Only set it when this host is behind NAT and cannot see its own public address.', max_length=64),
        ),
    ]
