# Generated by Django 4.2.30 on 2026-08-31 07:18

from django.db import migrations, models


def bump_aeps_ftype_default(apps, schema_editor):
    Config = apps.get_model('aeps', 'AepsProviderConfig')
    Config.objects.filter(capture_ftype_aeps='0').update(capture_ftype_aeps='2')


class Migration(migrations.Migration):

    dependencies = [
        ('aeps', '0008_alter_aepsproviderconfig_egress_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aepsproviderconfig',
            name='capture_ftype_aeps',
            field=models.CharField(
                choices=[('0', '0 — FMR'), ('1', '1 — FIR'), ('2', '2 — Full image')],
                default='2',
                help_text='fType requested for 2FA and AEPS product captures (2 = FMR+FIR; Mantra L1)',
                max_length=1,
            ),
        ),
        migrations.RunPython(bump_aeps_ftype_default, migrations.RunPython.noop),
    ]
