# Generated by Django 4.2.29 on 2026-05-22 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('event_key', models.CharField(db_index=True, max_length=80)),
                ('idempotency_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('phone_masked', models.CharField(blank=True, default='', max_length=20)),
                ('template_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, max_length=16)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=64)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('error_message', models.TextField(blank=True, default='')),
                ('context_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'sms_delivery_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('event_key', models.CharField(db_index=True, max_length=80, unique=True)),
                ('module', models.CharField(db_index=True, max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(db_index=True, default=False)),
                ('template_id', models.CharField(blank=True, default='', max_length=64)),
                ('variable_schema', models.JSONField(blank=True, default=list)),
                ('sample_variables', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'sms_notification_templates',
                'ordering': ['module', 'event_key'],
            },
        ),
        migrations.CreateModel(
            name='SmsProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, default='default', max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('msg91', 'MSG91'), ('console', 'Console (dev log only)')], default='msg91', max_length=32)),
                ('auth_key_encrypted', models.TextField(blank=True, default='')),
                ('sender_id', models.CharField(blank=True, default='', max_length=20)),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('api_base_url', models.CharField(blank=True, default='https://control.msg91.com', help_text='MSG91 API host (no trailing slash).', max_length=255)),
                ('route', models.CharField(blank=True, default='', max_length=32)),
                ('country_code', models.CharField(default='91', max_length=4)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, default='', max_length=32)),
                ('last_test_error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'sms_provider_configs',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='smsproviderconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('is_active',), name='uniq_sms_active_config'),
        ),
        migrations.AddField(
            model_name='smsdeliverylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_delivery_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
