# Generated by Django 4.2.29 on 2026-05-24 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('event_key', models.CharField(db_index=True, max_length=80, unique=True)),
                ('module', models.CharField(db_index=True, max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(db_index=True, default=False)),
                ('subject_template', models.CharField(blank=True, default='', max_length=255)),
                ('body_html_template', models.TextField(blank=True, default='')),
                ('body_plain_template', models.TextField(blank=True, default='')),
                ('variable_schema', models.JSONField(blank=True, default=list)),
                ('sample_variables', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'email_notification_templates',
                'ordering': ['module', 'event_key'],
            },
        ),
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('event_key', models.CharField(db_index=True, max_length=80)),
                ('idempotency_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('to_email_masked', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, max_length=16)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('context_json', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_delivery_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_delivery_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
