# Generated by Django 4.2.30 on 2026-07-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emailnotificationtemplate_emaildeliverylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnotificationtemplate',
            name='variable_map',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
