# Generated by Django 4.2.30 on 2026-08-06 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0006_profit_wallet_enterprise"),
        ("wallets", "0003_profit_wallet_enterprise"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "adjustment_id",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                (
                    "wallet_type",
                    models.CharField(
                        choices=[("main", "Main Wallet"), ("bbps", "BBPS Wallet")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[("CREDIT", "Credit"), ("DEBIT", "Debit")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        help_text="Original transaction reference / UTR / service id being corrected.",
                        max_length=100,
                    ),
                ),
                (
                    "reason_category",
                    models.CharField(
                        choices=[
                            ("failed_transaction", "Failed transaction"),
                            ("amount_not_reflected", "Amount not reflected"),
                            ("transaction_mismatch", "Transaction mismatch"),
                            ("refund_reversal", "Refund / reversal"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(help_text="Mandatory free-text justification."),
                ),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("balance_after", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "adjusted_by_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Immutable display name of the admin at time of adjustment.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        db_index=True,
                        default="SUCCESS",
                        max_length=10,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, default="")),
                (
                    "adjusted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_adjustments_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "passbook_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_adjustments",
                        to="transactions.passbookentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Target user whose wallet was adjusted.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_adjustments",
                        to="wallets.wallettransaction",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_adjustments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="wallet_adju_user_id_64367c_idx",
                    ),
                    models.Index(
                        fields=["adjustment_type", "created_at"],
                        name="wallet_adju_adjustm_d3b453_idx",
                    ),
                    models.Index(
                        fields=["reference_number"],
                        name="wallet_adju_referen_598041_idx",
                    ),
                    models.Index(
                        fields=["wallet_type", "created_at"],
                        name="wallet_adju_wallet__b5419f_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="wallet_adju_status_8b6446_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="walletadjustment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), ("status", "SUCCESS")),
                fields=("user", "reference_number", "adjustment_type"),
                name="uniq_wallet_adj_user_ref_type_success",
            ),
        ),
    ]
