# Generated by Django 4.2.29 on 2026-06-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_kycprofilesyncaudit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kycprofilesyncaudit',
            new_name='kyc_profile_user_id_9931cd_idx',
            old_name='kyc_prof_sync_user_st_idx',
        ),
    ]
