# Generated by Django 4.2.30 on 2026-07-14 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_rename_kyc_prof_sync_user_st_idx_kyc_profile_user_id_9931cd_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kyc',
            name='decision_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_approval', 'Awaiting Approval'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='KycApprovalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], db_index=True, max_length=20)),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_approval_actions', to=settings.AUTH_USER_MODEL)),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_audits', to='users.kyc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_approval_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_approval_audits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='kyc_approva_user_id_804094_idx'), models.Index(fields=['decision', 'created_at'], name='kyc_approva_decisio_11bbe7_idx')],
            },
        ),
    ]
