# Generated by Django 4.2.27 on 2026-08-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_role_history'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userrolehistory',
            new_name='user_role_h_user_id_92b6f5_idx',
            old_name='user_role_hist_user_created',
        ),
        migrations.RenameIndex(
            model_name='userrolehistory',
            new_name='user_role_h_member__b4e53f_idx',
            old_name='user_role_hist_member_created',
        ),
    ]
