# Generated by Django 4.2.30 on 2026-09-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_user_role_hist_user_created_user_role_h_user_id_92b6f5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycapprovalaudit',
            name='decision',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('request_resubmit', 'Request resubmit')], db_index=True, max_length=20),
        ),
    ]
