# Generated by Django 4.2.30 on 2026-07-22 17:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0010_session_security_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_location_enforcement_enabled', models.BooleanField(default=True, help_text='Require successful IP + geolocation capture on login/refresh.')),
                ('audit_logging_enabled', models.BooleanField(default=True, help_text='Persist per-user login/session audit events.')),
                ('single_session_enforcement_enabled', models.BooleanField(default=True, help_text='Terminate prior sessions when a user logs in elsewhere (unless allow_concurrent_sessions).')),
                ('idle_timeout_minutes', models.PositiveSmallIntegerField(default=5, help_text='Minutes of inactivity before the session expires (1–60).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_security_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session security settings',
                'verbose_name_plural': 'Session security settings',
                'db_table': 'session_security_settings',
            },
        ),
        migrations.CreateModel(
            name='UserLoginAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_attempted', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('event_type', models.CharField(choices=[('login_success', 'Login success'), ('login_failure', 'Login failure'), ('logout', 'Logout'), ('session_replaced', 'Session replaced'), ('session_rejected', 'Session rejected'), ('idle_timeout', 'Idle timeout'), ('refresh_denied', 'Refresh denied'), ('geo_capture_failed', 'Geo capture failed')], db_index=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='authentication.usersession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_login_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_login__user_id_1d7ddd_idx'), models.Index(fields=['event_type', 'created_at'], name='user_login__event_t_4008bd_idx')],
            },
        ),
    ]
