# Generated by Django 4.2.27 on 2026-08-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_security', '0001_session_security_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userloginauditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'User activity audit log', 'verbose_name_plural': 'User activity audit logs'},
        ),
        migrations.AlterField(
            model_name='sessionsecuritysettings',
            name='audit_logging_enabled',
            field=models.BooleanField(default=True, help_text='Persist per-user login/session and activity audit events.'),
        ),
        migrations.AlterField(
            model_name='userloginauditlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login success'), ('login_failure', 'Login failure'), ('logout', 'Logout'), ('session_replaced', 'Session replaced'), ('session_rejected', 'Session rejected'), ('idle_timeout', 'Idle timeout'), ('refresh_denied', 'Refresh denied'), ('geo_capture_failed', 'Geo capture failed'), ('payin_created', 'Pay-in created'), ('payin_success', 'Pay-in success'), ('payin_failed', 'Pay-in failed'), ('payout_created', 'Payout created'), ('payout_success', 'Payout success'), ('payout_failed', 'Payout failed'), ('bbps_payment', 'BBPS payment'), ('wallet_transfer', 'Wallet transfer'), ('access_controls_changed', 'Access controls changed'), ('role_changed', 'Role changed'), ('user_disabled', 'User disabled'), ('user_enabled', 'User enabled')], db_index=True, max_length=32),
        ),
    ]
