# Generated by Django 4.2.29 on 2026-08-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_system_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmaintenanceconfig',
            name='aeps_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='systemmaintenanceconfig',
            name='aeps_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='systemmaintenanceauditlog',
            name='module',
            field=models.CharField(choices=[('pay_in', 'Pay-in'), ('payout', 'Payout'), ('bbps', 'BBPS'), ('aeps', 'AEPS'), ('all', 'All modules')], db_index=True, max_length=20),
        ),
    ]
