# Generated by Django 4.2.30 on 2026-09-08 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_platform_appearance_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('group', models.CharField(blank=True, default='', max_length=64)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'app_modules',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=20)),
                ('module_code', models.CharField(db_index=True, max_length=64)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'role_module_permissions',
                'ordering': ['role', 'module_code'],
                'unique_together': {('role', 'module_code')},
            },
        ),
        migrations.CreateModel(
            name='PortalAccessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_usage_mode_enabled', models.BooleanField(db_index=True, default=False)),
                ('test_usage_title', models.CharField(blank=True, default='Test usage mode', max_length=200)),
                ('test_usage_message', models.TextField(blank=True, default='The portal is currently in test usage mode. Contact your administrator.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_access_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portal access config',
                'verbose_name_plural': 'Portal access config',
                'db_table': 'portal_access_config',
            },
        ),
    ]
