# Generated by Django 4.2.30 on 2026-09-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_super_admin_rbac'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmaintenanceconfig',
            name='cms_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='systemmaintenanceconfig',
            name='cms_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='systemmaintenanceauditlog',
            name='module',
            field=models.CharField(choices=[('pay_in', 'Pay-in'), ('payout', 'Payout'), ('bbps', 'BBPS'), ('aeps', 'AEPS'), ('cms', 'CMS'), ('all', 'All modules')], db_index=True, max_length=20),
        ),
    ]
