# Generated by Django 4.2.7 on 2026-04-17 06:33

from django.db import migrations, models


def create_admin_profit_wallets(apps, schema_editor):
    Wallet = apps.get_model('wallets', 'Wallet')
    User = apps.get_model('authentication', 'User')

    admin_users = User.objects.filter(is_active=True, role__iexact='Admin').only('id')
    for user in admin_users.iterator(chunk_size=200):
        Wallet.objects.get_or_create(
            user_id=user.id,
            wallet_type='profit',
            defaults={'balance': 0},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_enterprise_reporting_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('main', 'Main Wallet'), ('commission', 'Commission Wallet'), ('bbps', 'BBPS Wallet'), ('profit', 'Profit Wallet')], db_index=True, max_length=20),
        ),
        migrations.RunPython(create_admin_profit_wallets, noop_reverse),
    ]
