# Generated by Django 4.2.30 on 2026-09-19 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallets", "0003_profit_wallet_enterprise"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="held_balance",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Amount reserved for in-flight operations (BBPS AWAITED, CMS holds).",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True after consolidation drained this non-main wallet to zero.",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("credit", "Credit"),
                    ("debit", "Debit"),
                    ("hold", "Hold"),
                    ("release", "Release"),
                    ("settle", "Settle"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="WalletMergeAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "main_before",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "bbps_before",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "commission_before",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "profit_before",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "merged_total",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Sum of all source balances folded into main (excludes main_before).",
                        max_digits=18,
                    ),
                ),
                (
                    "main_after",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "bridge_service_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("merged", "Merged"),
                            ("rolled_back", "Rolled back"),
                            ("dry_run", "Dry run"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_merge_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wallet_merge_audits",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="wallet_merg_status_acff45_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="wallet_merg_user_id_f3edca_idx"
                    ),
                ],
            },
        ),
    ]
