# Generated by Django 4.2.27 on 2026-01-26 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('transaction_type', models.CharField(choices=[('payin', 'Pay In'), ('payout', 'Pay Out'), ('bbps', 'BBPS')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('platform_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('service_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_type', models.CharField(blank=True, max_length=50, null=True)),
                ('biller', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'transaction_type', 'status', 'created_at'], name='transaction_user_id_3eaeaf_idx'), models.Index(fields=['service_id'], name='transaction_service_54cc97_idx')],
            },
        ),
        migrations.CreateModel(
            name='PassbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('service', models.CharField(max_length=100)),
                ('service_id', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passbook_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passbook_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='passbook_en_user_id_618863_idx'), models.Index(fields=['service_id'], name='passbook_en_service_00d473_idx')],
            },
        ),
    ]
