# Generated by Django 4.2.7 on 2026-04-08 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('role_at_time', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('payin', 'Pay-in')], db_index=True, default='payin', max_length=20)),
                ('reference_service_id', models.CharField(db_index=True, max_length=100)),
                ('wallet_type', models.CharField(choices=[('main', 'Main'), ('commission', 'Commission')], default='commission', max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'commission_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='passbookentry',
            name='wallet_type',
            field=models.CharField(choices=[('main', 'Main'), ('commission', 'Commission')], db_index=True, default='main', help_text='Which wallet this line applies to.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='passbookentry',
            index=models.Index(fields=['user', 'wallet_type', 'created_at'], name='passbook_en_user_id_eff8f6_idx'),
        ),
        migrations.AddField(
            model_name='commissionledger',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for rows absorbed by platform with no wallet user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='commissionledger',
            index=models.Index(fields=['reference_service_id'], name='commission__referen_6f1f36_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionledger',
            index=models.Index(fields=['user', 'source', 'created_at'], name='commission__user_id_ad6abc_idx'),
        ),
    ]
