# Generated by Django 4.2.7 on 2026-04-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_enterprise_payin_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passbookentry',
            name='wallet_type',
            field=models.CharField(choices=[('main', 'Main'), ('commission', 'Commission'), ('bbps', 'BBPS')], db_index=True, default='main', help_text='Which wallet this line applies to.', max_length=20),
        ),
    ]
