# Generated by Django 4.2.7 on 2026-04-17 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_enterprise_reporting_fields(apps, schema_editor):
    Transaction = apps.get_model('transactions', 'Transaction')
    CommissionLedger = apps.get_model('transactions', 'CommissionLedger')
    PassbookEntry = apps.get_model('transactions', 'PassbookEntry')
    User = apps.get_model('authentication', 'User')

    fam_map = {'payin': 'payin', 'payout': 'payout', 'bbps': 'bbps'}

    for t in Transaction.objects.iterator(chunk_size=500):
        fields = []
        if not (t.service_family or '').strip():
            t.service_family = fam_map.get(t.transaction_type, 'other')
            fields.append('service_family')
        if t.user_id and not (t.agent_user_code or '').strip():
            try:
                u = User.objects.get(pk=t.user_id)
            except User.DoesNotExist:
                u = None
            if u:
                t.agent_user_id = u.pk
                t.agent_role_at_time = getattr(u, 'role', '') or ''
                t.agent_user_code = str(getattr(u, 'user_id', None) or '')
                name = ''
                try:
                    prof = getattr(u, 'profile', None)
                    if prof is not None:
                        name = (getattr(prof, 'full_name', None) or '').strip()
                except Exception:
                    name = ''
                if not name:
                    name = (getattr(u, 'email', None) or '') or str(u.pk)
                t.agent_name_snapshot = name[:255]
                fields.extend(
                    ['agent_user', 'agent_role_at_time', 'agent_user_code', 'agent_name_snapshot']
                )
        if not t.bank_txn_id and (t.reference or '').strip():
            t.bank_txn_id = (t.reference or '')[:191]
            fields.append('bank_txn_id')
        if fields:
            t.save(update_fields=fields)

    for row in CommissionLedger.objects.iterator(chunk_size=500):
        meta = row.meta if isinstance(row.meta, dict) else {}
        code = str(meta.get('source_user_code') or '')
        role = str(meta.get('source_role') or '')
        snap = str(meta.get('source_name') or code or '')
        if (row.source_user_code or '').strip() or (row.source_role or '').strip():
            continue
        if code or role or snap:
            row.source_user_code = code[:30]
            row.source_role = role[:50]
            row.source_name_snapshot = snap[:255]
            row.save(update_fields=['source_user_code', 'source_role', 'source_name_snapshot'])

    for pe in PassbookEntry.objects.filter(initiator_user__isnull=True).iterator(chunk_size=500):
        if pe.user_id:
            pe.initiator_user_id = pe.user_id
            try:
                u = User.objects.get(pk=pe.user_id)
            except User.DoesNotExist:
                u = None
            if u:
                pe.initiator_role_at_time = getattr(u, 'role', '') or ''
                pe.initiator_user_code = str(getattr(u, 'user_id', None) or '')
                name = ''
                try:
                    prof = getattr(u, 'profile', None)
                    if prof is not None:
                        name = (getattr(prof, 'full_name', None) or '').strip()
                except Exception:
                    name = ''
                if not name:
                    name = (getattr(u, 'email', None) or '') or str(u.pk)
                pe.initiator_name_snapshot = name[:255]
                pe.save(
                    update_fields=[
                        'initiator_user',
                        'initiator_role_at_time',
                        'initiator_user_code',
                        'initiator_name_snapshot',
                    ]
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    # PostgreSQL: ALTER TYPE + CREATE INDEX in one atomic block can raise
    # "pending trigger events"; run non-atomically for this data migration.
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0004_passbookentry_service_charge_principal'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='passbookentry',
            name='passbook_en_service_00d473_idx',
        ),
        migrations.AddField(
            model_name='commissionledger',
            name='source_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='commissionledger',
            name='source_role',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='commissionledger',
            name='source_user_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='passbookentry',
            name='initiator_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='passbookentry',
            name='initiator_role_at_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='passbookentry',
            name='initiator_user',
            field=models.ForeignKey(blank=True, help_text='Business actor that caused this line (e.g. retailer on a commission credit).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_passbook_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passbookentry',
            name='initiator_user_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='agent_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='agent_role_at_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='agent_user',
            field=models.ForeignKey(blank=True, help_text='Actor / wallet owner snapshot for reporting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='agent_user_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_txn_id',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_family',
            field=models.CharField(blank=True, choices=[('payin', 'Pay-in'), ('payout', 'Payout'), ('bbps', 'BBPS'), ('wallet_transfer', 'Wallet transfer'), ('commission', 'Commission'), ('other', 'Other')], db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='commissionledger',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='passbookentry',
            name='closing_balance',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='passbookentry',
            name='credit_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='passbookentry',
            name='debit_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='passbookentry',
            name='opening_balance',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='passbookentry',
            name='principal_amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Underlying transaction amount excluding charge when applicable.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='passbookentry',
            name='service_charge',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Fees/charges for this line (e.g. payout slab); 0 when N/A.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='charge',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=18, null=True),
        ),
        migrations.AddIndex(
            model_name='commissionledger',
            index=models.Index(fields=['user', 'created_at'], name='commission__user_id_3e5355_idx'),
        ),
        migrations.AddIndex(
            model_name='passbookentry',
            index=models.Index(fields=['service_id', 'created_at'], name='passbook_en_service_86fce2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='transaction_transac_6dc4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['agent_user_code', 'created_at'], name='transaction_agent_u_de5613_idx'),
        ),
        migrations.RunPython(backfill_enterprise_reporting_fields, noop_reverse),
    ]
