# Generated by Django 4.2.7 on 2026-04-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_enterprise_reporting_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionledger',
            name='source',
            field=models.CharField(choices=[('payin', 'Pay-in'), ('profit', 'Platform profit')], db_index=True, default='payin', max_length=20),
        ),
        migrations.AlterField(
            model_name='commissionledger',
            name='wallet_type',
            field=models.CharField(choices=[('main', 'Main'), ('commission', 'Commission'), ('profit', 'Profit')], default='commission', max_length=20),
        ),
        migrations.AlterField(
            model_name='passbookentry',
            name='wallet_type',
            field=models.CharField(choices=[('main', 'Main'), ('commission', 'Commission'), ('bbps', 'BBPS'), ('profit', 'Profit')], db_index=True, default='main', help_text='Which wallet this line applies to.', max_length=20),
        ),
    ]
