# Generated by Django 4.2.30 on 2026-09-01 04:52

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_profit_wallet_enterprise"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="commissionledger",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["meta"], name="commission_ledger_meta_gin"
            ),
        ),
    ]
