# Generated by Django 4.2.30 on 2026-09-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_performance_report_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="commissionledger",
            name="customer_charge",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Total charge the customer paid on this transaction (same for all slices).",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="commissionledger",
            name="entry_kind",
            field=models.CharField(
                choices=[("commission", "Commission"), ("service_fee", "Service fee")],
                db_index=True,
                default="commission",
                help_text="commission = downline earning; service_fee = platform revenue from a configured charge.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="commissionledger",
            name="module",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Product module: payin, bbps, payout, bank_verification, aeps, cms.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="commissionledger",
            name="slice_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Stable slice id for idempotency (e.g. admin_absorbed, gateway_absorbed, Super Distributor).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="commissionledger",
            name="source",
            field=models.CharField(
                choices=[
                    ("payin", "Pay-in"),
                    ("profit", "Platform profit"),
                    ("bbps", "BBPS"),
                    ("payout", "Payout"),
                    ("bank_verification", "Bank verification"),
                    ("aeps", "AEPS"),
                    ("cms", "CMS"),
                ],
                db_index=True,
                default="payin",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="commissionledger",
            name="wallet_type",
            field=models.CharField(
                choices=[
                    ("main", "Main"),
                    ("commission", "Commission"),
                    ("profit", "Profit"),
                ],
                default="main",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="commissionledger",
            index=models.Index(
                fields=["module", "entry_kind", "created_at"],
                name="commission__module_ddacc2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="commissionledger",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("user__isnull", False), models.Q(("slice_key", ""), _negated=True)
                ),
                fields=("reference_service_id", "user", "slice_key"),
                name="commission_ledger_idempotent_slice",
            ),
        ),
    ]
