# Generated by Django 4.2.30 on 2026-09-18 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('bc_login_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('merchant_pin_encrypted', models.TextField(blank=True, default='')),
                ('mobile_number', models.CharField(blank=True, default='', max_length=15)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='inactive', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cms_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms_agent_profiles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CmsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('merchant_transaction_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('fp_transaction_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('type_of_transaction', models.CharField(db_index=True, default='CDC', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='initiated', max_length=20)),
                ('bc_login_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('agent_login_id', models.CharField(blank=True, default='', max_length=64)),
                ('drop_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('remarks', models.CharField(blank=True, default='', max_length=500)),
                ('provider_meta', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cms.cmsagentprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cms_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CmsWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('held_balance', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cms_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms_wallets',
            },
        ),
        migrations.CreateModel(
            name='CmsWalletEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('entry_type', models.CharField(choices=[('fund', 'Fund from main'), ('unfund', 'Return to main'), ('hold', 'Hold'), ('settle', 'Settle hold'), ('release', 'Release hold'), ('adjustment', 'Adjustment')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('opening_balance', models.DecimalField(decimal_places=4, max_digits=18)),
                ('closing_balance', models.DecimalField(decimal_places=4, max_digits=18)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_entries', to='cms.cmstransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cms.cmswallet')),
            ],
            options={
                'db_table': 'cms_wallet_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CmsProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, default='default', max_length=100, unique=True)),
                ('environment', models.CharField(choices=[('uat', 'UAT'), ('prod', 'Production')], db_index=True, default='uat', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('login_type', models.CharField(default='2', max_length=8)),
                ('super_merchant_id', models.CharField(blank=True, default='', max_length=64)),
                ('cms_base_url', models.URLField(blank=True, default='', max_length=500)),
                ('login_path', models.CharField(default='/UberCMSBC/#/login', max_length=200)),
                ('secrets_encrypted', models.TextField(blank=True, default='')),
                ('hash_template', models.CharField(default='{payload}{secret_key}', max_length=64)),
                ('allowed_inbound_ips', models.JSONField(blank=True, default=list)),
                ('debug_mode', models.BooleanField(default=False, help_text='When on, store full request/response bodies on inbound CMS webhooks')),
                ('hold_ttl_hours', models.PositiveIntegerField(default=24, help_text='Hours before an initiated hold is auto-released as expired')),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_provider_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms_provider_configs',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CmsLaunchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('opened', 'Opened'), ('consumed', 'Consumed'), ('expired', 'Expired')], db_index=True, default='created', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch_sessions', to='cms.cmsagentprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_launch_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms_launch_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CmsEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('access_request', 'Access request')], default='manual', max_length=32)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_reason', models.CharField(blank=True, default='', max_length=500)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_entitlements_assigned', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cms_entitlement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms_entitlements',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CmsApiAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('merchant_transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('fp_transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_summary', models.JSONField(blank=True, default=dict)),
                ('response_summary', models.JSONField(blank=True, default=dict)),
                ('debug_enabled', models.BooleanField(db_index=True, default=False)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_api_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms_api_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cmstransaction',
            index=models.Index(fields=['user', '-created_at'], name='cms_transac_user_id_99da26_idx'),
        ),
        migrations.AddIndex(
            model_name='cmstransaction',
            index=models.Index(fields=['status', '-created_at'], name='cms_transac_status_627e1b_idx'),
        ),
    ]
