# Generated by Django 4.2.7 on 2026-04-17 04:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='charge',
            field=models.DecimalField(decimal_places=4, default=Decimal('5.0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='total_deducted',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
    ]
