# Generated by Django 4.2.27 on 2026-04-22 14:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbps', '0003_bbpsapiauditlog_bbpsbillermaster_bbpscomplaint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BbpsCategoryCommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('rule_code', models.CharField(db_index=True, max_length=80)),
                ('commission_type', models.CharField(choices=[('flat', 'Flat'), ('percentage', 'Percentage')], default='flat', max_length=20)),
                ('value', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('min_commission', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('max_commission', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'bbps_category_commission_rule',
                'ordering': ['-is_active', '-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BbpsServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'bbps_service_category',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='bbpspaymentattempt',
            name='commission_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='bbpspaymentattempt',
            name='commission_rule_code',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='bbpspaymentattempt',
            name='commission_rule_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='commission_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='commission_rule_code',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='commission_rule_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='BbpsServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('provider_type', models.CharField(choices=[('operator', 'Operator'), ('bank', 'Bank'), ('utility', 'Utility'), ('other', 'Other')], default='other', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveIntegerField(db_index=True, default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='bbps.bbpsservicecategory')),
            ],
            options={
                'db_table': 'bbps_service_provider',
                'ordering': ['category__display_order', 'priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BbpsProviderBillerMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveIntegerField(db_index=True, default=0)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('biller_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_maps', to='bbps.bbpsbillermaster')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biller_maps', to='bbps.bbpsserviceprovider')),
            ],
            options={
                'db_table': 'bbps_provider_biller_map',
                'ordering': ['provider__category__display_order', 'provider__priority', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BbpsCommissionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('changed_by_user_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(db_index=True, default='upsert', max_length=30)),
                ('previous_snapshot', models.JSONField(blank=True, default=dict)),
                ('new_snapshot', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='bbps.bbpscategorycommissionrule')),
            ],
            options={
                'db_table': 'bbps_commission_audit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bbpscategorycommissionrule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='bbps.bbpsservicecategory'),
        ),
        migrations.AddConstraint(
            model_name='bbpsserviceprovider',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('category', 'code'), name='uniq_bbps_provider_code_per_category'),
        ),
        migrations.AddConstraint(
            model_name='bbpsproviderbillermap',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('provider', 'biller_master'), name='uniq_bbps_provider_biller_map'),
        ),
        migrations.AddConstraint(
            model_name='bbpscategorycommissionrule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('category', 'rule_code'), name='uniq_bbps_commission_rule_code_per_category'),
        ),
    ]
