# Generated by Django 4.2.29 on 2026-04-30 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbps', '0005_backfill_approval_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbpsbillermaster',
            name='is_active_local',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='bbpsbillermaster',
            name='last_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bbpsbillermaster',
            name='last_sync_request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='bbpsbillermaster',
            name='last_sync_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bbpsbillermaster',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bbpsbillermaster',
            name='source_type',
            field=models.CharField(blank=True, db_index=True, default='synced', max_length=20),
        ),
        migrations.AddField(
            model_name='bbpsbillermaster',
            name='updated_by_admin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bbpsbillermaster',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='BbpsSyncUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('usage_date', models.DateField(db_index=True)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('requested_ids_count', models.PositiveIntegerField(default=0)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('last_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bbps_sync_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bbps_sync_usage_log',
                'ordering': ['-usage_date', '-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='bbpssyncusagelog',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('usage_date',), name='uniq_bbps_sync_usage_per_day'),
        ),
    ]
