# Generated by Django 4.2.29 on 2026-05-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbps', '0008_bbpscomplaint_billavenue_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbpscomplaint',
            name='billavenue_request_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='requestId sent on BillAvenue complaint register call (35 chars; for support).', max_length=50),
        ),
    ]
