# Generated by Django 4.2.30 on 2026-08-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbps', '0009_alter_bbpscomplaint_billavenue_request_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bbpssyncusagelog',
            name='uniq_bbps_sync_usage_per_day',
        ),
        migrations.AddField(
            model_name='bbpsbillermaster',
            name='environment',
            field=models.CharField(choices=[('uat', 'UAT'), ('prod', 'Production')], db_index=True, default='uat', help_text='BillAvenue environment this MDM row was synced from (uat|prod).', max_length=10),
        ),
        migrations.AddField(
            model_name='bbpssyncusagelog',
            name='environment',
            field=models.CharField(choices=[('uat', 'UAT'), ('prod', 'Production')], db_index=True, default='uat', max_length=10),
        ),
        migrations.AlterField(
            model_name='bbpsbillermaster',
            name='biller_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='bbpsbillermaster',
            index=models.Index(fields=['environment', 'biller_category'], name='bbps_biller_environ_8af4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='bbpsbillermaster',
            index=models.Index(fields=['environment', 'is_active_local'], name='bbps_biller_environ_d71452_idx'),
        ),
        migrations.AddConstraint(
            model_name='bbpsbillermaster',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('environment', 'biller_id'), name='uniq_bbps_biller_id_per_environment'),
        ),
        migrations.AddConstraint(
            model_name='bbpssyncusagelog',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('usage_date', 'environment'), name='uniq_bbps_sync_usage_per_day_env'),
        ),
    ]
