# Generated by Django 4.2.30 on 2026-08-04 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbps', '0010_dual_env_credentials_and_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BbpsMdmImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('environment', models.CharField(choices=[('uat', 'UAT'), ('prod', 'Production')], db_index=True, max_length=10)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('partial', 'Partial'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('total_ids', models.PositiveIntegerField(default=0)),
                ('synced_ids', models.PositiveIntegerField(default=0)),
                ('failed_ids', models.PositiveIntegerField(default=0)),
                ('pending_ids', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bbps_mdm_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bbps_mdm_import_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BbpsMdmImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('biller_id', models.CharField(db_index=True, max_length=40)),
                ('biller_name', models.CharField(blank=True, default='', max_length=255)),
                ('biller_category', models.CharField(blank=True, default='', max_length=120)),
                ('biller_coverage', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bbps.bbpsmdmimportjob')),
            ],
            options={
                'db_table': 'bbps_mdm_import_item',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='bbpsmdmimportjob',
            index=models.Index(fields=['environment', 'status'], name='bbps_mdm_im_environ_cc48ed_idx'),
        ),
        migrations.AddIndex(
            model_name='bbpsmdmimportitem',
            index=models.Index(fields=['job', 'status'], name='bbps_mdm_im_job_id_636668_idx'),
        ),
        migrations.AddConstraint(
            model_name='bbpsmdmimportitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('job', 'biller_id'), name='uniq_bbps_mdm_import_item_per_job'),
        ),
    ]
