# Generated by Django 4.2.30 on 2026-08-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bbps", "0011_mdm_excel_import_queue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bbpsmdmimportjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("partial", "Partial"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="queued",
                max_length=20,
            ),
        ),
    ]
