# Generated by Django 4.2.29 on 2026-08-06 07:01

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bbps", "0012_mdm_import_cancelled_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BbpsProviderFloat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "environment",
                    models.CharField(
                        choices=[("uat", "UAT"), ("prod", "Production")],
                        db_index=True,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "low_balance_threshold",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Admin warning when tracked balance falls at or below this value.",
                        max_digits=18,
                    ),
                ),
                (
                    "enforcement_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="When True, BBPS payments are blocked if float is insufficient.",
                    ),
                ),
                ("last_manual_set_at", models.DateTimeField(blank=True, null=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bbps_provider_float_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bbps_provider_float",
                "ordering": ["environment"],
            },
        ),
        migrations.CreateModel(
            name="BbpsProviderFloatLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("environment", models.CharField(db_index=True, max_length=10)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("MANUAL_SET", "Manual set"),
                            ("AUTO_DEBIT", "Auto debit"),
                            ("AUTO_CREDIT", "Auto credit"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("balance_after", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "service_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                (
                    "performed_by_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "float_row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="bbps.bbpsproviderfloat",
                    ),
                ),
                (
                    "payment_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_float_ledger",
                        to="bbps.bbpspaymentattempt",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bbps_provider_float_ledger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bbps_provider_float_ledger",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["environment", "created_at"],
                        name="bbps_provid_environ_8a5efd_idx",
                    ),
                    models.Index(
                        fields=["entry_type", "created_at"],
                        name="bbps_provid_entry_t_dce165_idx",
                    ),
                    models.Index(
                        fields=["service_id", "entry_type"],
                        name="bbps_provid_service_b59c76_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="bbpsproviderfloatledger",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_deleted", False), models.Q(("service_id", ""), _negated=True)
                ),
                fields=("service_id", "entry_type"),
                name="uniq_bbps_provider_float_ledger_service_entry",
            ),
        ),
    ]
