# Generated by Django 4.2.29 on 2026-08-06 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bbps", "0013_provider_float"),
    ]

    operations = [
        migrations.AddField(
            model_name="bbpsdepositenquirysnapshot",
            name="agents",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="bbpsdepositenquirysnapshot",
            name="environment",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="bbpsdepositenquirysnapshot",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bbps_deposit_enquiries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bbpsdepositenquirysnapshot",
            name="response_code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="bbpsdepositenquirysnapshot",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("PARTIAL", "Partial"),
                ],
                db_index=True,
                default="SUCCESS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bbpsdepositenquirysnapshot",
            name="transaction_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="bbpsdepositenquirysnapshot",
            index=models.Index(
                fields=["environment", "created_at"],
                name="bbps_deposi_environ_14449b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bbpsdepositenquirysnapshot",
            index=models.Index(
                fields=["from_date", "to_date"], name="bbps_deposi_from_da_0b4203_idx"
            ),
        ),
    ]
