# Generated by Django 4.2.30 on 2026-08-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bbps", "0015_catalog_ux_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bbpscataloguxsettings",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="bbpscataloguxsettings",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
