# Generated by Django 4.2.30 on 2026-09-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bbps", "0016_alter_bbpscataloguxsettings_created_at_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="billpayment",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["status", "created_at"],
                name="billpay_status_created_rpt",
            ),
        ),
    ]
