# Generated by Django 4.2.30 on 2026-09-19 03:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bbps", "0018_bbpsbillermaster_local_visibility_hold"),
    ]

    operations = [
        migrations.AddField(
            model_name="bbpspaymentattempt",
            name="wallet_hold_amount",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                help_text="Amount currently held on the user main wallet for this attempt.",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="bbpspaymentattempt",
            name="wallet_settled_amount",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                help_text="Amount settled (debited) from the user main wallet on SUCCESS.",
                max_digits=18,
            ),
        ),
    ]
