# Generated by Django 4.2.7 on 2026-04-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Super Distributor', 'Super Distributor'), ('Master Distributor', 'Master Distributor'), ('Distributor', 'Distributor'), ('Retailer', 'Retailer')], default='Retailer', max_length=20),
        ),
    ]
