# Generated by Django 4.2.29 on 2026-05-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_otp_delivery_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('password-reset', 'Password Reset'), ('mpin-reset', 'MPIN Reset'), ('aadhaar-verification', 'Aadhaar Verification')], default='password-reset', max_length=30),
        ),
    ]
