# Generated by Django 4.2.30 on 2026-07-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_backfill_member_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_concurrent_sessions',
            field=models.BooleanField(db_index=True, default=False, help_text='When True, user may keep multiple active sessions (admin exception).'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='jti',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='location',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersession',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='termination_reason',
            field=models.CharField(blank=True, choices=[('replaced', 'Replaced by new login'), ('logout', 'Logout'), ('idle', 'Idle timeout'), ('admin', 'Admin terminated')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['jti', 'is_active'], name='user_sessio_jti_c499a4_idx'),
        ),
    ]
