# Generated by Django 4.2 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_session_security_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('Admin', 'Admin'),
                    ('Super Distributor', 'Super Distributor'),
                    ('Master Distributor', 'Master Distributor'),
                    ('Distributor', 'Distributor'),
                    ('Retailer', 'Retailer'),
                ],
                db_index=True,
                default='Retailer',
                max_length=20,
            ),
        ),
    ]
