# Generated by Django 4.2.30 on 2026-09-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_user_role_is_active_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_restricted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Read-only portal: no pay-in or payment outflows.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="payments_locked",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Block BBPS pay, payout, and wallet transfers; pay-in allowed unless restricted.",
            ),
        ),
    ]
