# Generated by Django 4.2.30 on 2026-09-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_performance_report_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_test_user',
            field=models.BooleanField(db_index=True, default=False, help_text='When Test usage mode is on, only Super Admin and test users may log in.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Super Distributor', 'Super Distributor'), ('Master Distributor', 'Master Distributor'), ('Distributor', 'Distributor'), ('Retailer', 'Retailer')], db_index=True, default='Retailer', max_length=20),
        ),
    ]
