export const EMPTY_ONBOARDING_FORM = {
  firstName: '',
  lastName: '',
  middleName: '',
  merchantPhoneNumber: '',
  emailId: '',
  merchantAddress1: '',
  merchantAddress2: '',
  merchantCityName: '',
  merchantDistrictName: '',
  merchantPinCode: '',
  merchantState: '',
  companyLegalName: '',
  companyType: '',
  userPan: '',
  aadhaarNumber: '',
  gstinNumber: '',
  companyOrShopPan: '',
  companyBankAccountNumber: '',
  bankIfscCode: '',
  companyBankName: '',
  bankBranchName: '',
  bankAccountName: '',
  shopName: '',
  shopAddress: '',
  shopCity: '',
  shopDistrict: '',
  shopState: '',
  shopPincode: '',
  merchantPanImage: '',
  maskedAadharImage: '',
  backgroundImageOfShop: '',
};

export const SETUP_STEPS = [
  { id: 'onboarding', label: 'Merchant details' },
  { id: 'ekyc', label: 'eKYC' },
  { id: 'ready', label: 'Ready' },
];
