"""
URL configuration for BBPS app.
"""
from django.urls import path
from apps.bbps import views

app_name = 'bbps'

urlpatterns = [
    path('categories/', views.get_categories_view, name='categories'),
    path('providers/<str:category>/', views.get_providers_view, name='providers'),
    path('billers/<str:biller_id>/schema/', views.biller_schema_view, name='biller-schema'),
    path('billers/<str:category>/', views.get_billers_view, name='billers'),
    path('quote/', views.quote_view, name='quote'),
    path('fetch-bill/', views.fetch_bill_view, name='fetch-bill'),
    path('pay/', views.pay_bill_view, name='pay'),
    path('payments/', views.bill_payments_list_view, name='payments'),
    path('payments/<int:payment_id>/', views.bill_payment_detail_view, name='payment-detail'),
    path('admin/config/', views.billavenue_config_view, name='billavenue-config'),
    path('admin/integration-health/', views.integration_health_view, name='integration-health'),
    path('admin/setup-readiness/', views.setup_readiness_view, name='setup-readiness'),
    path('admin/cache/refresh-providers/', views.refresh_provider_cache_view, name='refresh-provider-cache'),
    path('admin/governance/ops-summary/', views.governance_ops_summary_view, name='governance-ops-summary'),
    path('admin/governance/observability/', views.bbps_ops_observability_view, name='governance-observability'),
    path('admin/config/secrets/', views.billavenue_config_secrets_view, name='billavenue-config-secrets'),
    path('admin/agent-profiles/', views.billavenue_agent_profiles_view, name='billavenue-agent-profiles'),
    path('admin/mode-channel-policies/', views.billavenue_mode_channel_policies_view, name='billavenue-mode-channel-policies'),
    path('admin/service-categories/', views.service_categories_view, name='service-categories'),
    path('admin/service-providers/', views.service_providers_view, name='service-providers'),
    path('admin/billers/<str:biller_id>/catalog-summary/', views.biller_catalog_summary_view, name='biller-catalog-summary'),
    path('admin/billers/<str:biller_id>/payment-mapping/', views.biller_payment_mapping_view, name='biller-payment-mapping'),
    path('admin/biller-master/', views.biller_master_admin_view, name='biller-master-admin'),
    path('admin/biller-master/clear-all/', views.biller_master_admin_clear_all_view, name='biller-master-clear-all'),
    path('admin/biller-master/<int:pk>/', views.biller_master_admin_detail_view, name='biller-master-admin-detail'),
    path('admin/biller-master/<int:pk>/full-details/', views.biller_master_admin_full_detail_view, name='biller-master-full-details'),
    path('admin/biller-master/<int:pk>/disable/', views.biller_master_disable_view, name='biller-master-disable'),
    path('admin/biller-master/<int:pk>/enable/', views.biller_master_enable_view, name='biller-master-enable'),
    path('admin/sync-usage/today/', views.sync_usage_today_view, name='sync-usage-today'),
    path('admin/sync-usage/history/', views.sync_usage_history_view, name='sync-usage-history'),
    path('admin/provider-biller-maps/', views.provider_biller_maps_view, name='provider-biller-maps'),
    path('admin/mdm-catalog/summary/', views.mdm_catalog_summary_view, name='mdm-catalog-summary'),
    path('admin/mdm-catalog/publish/', views.mdm_catalog_publish_view, name='mdm-catalog-publish'),
    path('admin/mdm-catalog/bulk-publish/', views.mdm_catalog_bulk_publish_view, name='mdm-catalog-bulk-publish'),
    path('admin/commission-rules/', views.commission_rules_view, name='commission-rules'),
    path('admin/commission-audit/', views.commission_audit_view, name='commission-audit'),
    path('admin/sync-billers/', views.sync_billers_view, name='sync-billers'),
    path('admin/poll-status/', views.poll_status_view, name='poll-status'),
    path('admin/uat-readiness/', views.uat_readiness_checklist_view, name='uat-readiness'),
    path('admin/plans/pull/', views.plan_pull_view, name='plan-pull'),
    path('admin/deposit-enquiry/', views.deposit_enquiry_view, name='deposit-enquiry'),
    path('transactions/query/', views.transaction_query_view, name='transaction-query'),
    path('complaints/register/', views.complaint_register_view, name='complaint-register'),
    path('complaints/history/', views.complaint_history_view, name='complaint-history'),
    path('complaints/track/', views.complaint_track_view, name='complaint-track'),
    path('complaints/refresh-status/', views.complaint_refresh_status_view, name='complaint-refresh-status'),
    path('callback/billavenue/', views.billavenue_callback_view, name='billavenue-callback'),
]
