# Generated by Django 4.2.7 on 2026-04-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('admin_panel', '0002_announcement_image_optional_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='api_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_gateways', to='integrations.apimaster'),
        ),
    ]
