# Generated by Django 4.2.7 on 2026-04-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_paymentgateway_api_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutSlabConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(default='default', max_length=80, unique=True)),
                ('low_max_amount', models.DecimalField(decimal_places=4, default=24999, max_digits=18)),
                ('low_charge', models.DecimalField(decimal_places=4, default=7, max_digits=18)),
                ('high_charge', models.DecimalField(decimal_places=4, default=15, max_digits=18)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'payout_slab_config',
                'ordering': ['-is_active', 'id'],
            },
        ),
    ]
