# Generated by Django 4.2.30 on 2026-09-25 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0010_payout_vimopay_provider"),
        ("admin_panel", "0006_alter_smtpconfig_host_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="payoutgateway",
            name="api_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payout_gateways",
                to="integrations.apimaster",
            ),
        ),
    ]
