# Generated by Django 4.2.7 on 2026-04-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('provider_code', models.SlugField(max_length=80, unique=True)),
                ('provider_name', models.CharField(max_length=200)),
                ('provider_type', models.CharField(choices=[('kyc', 'KYC'), ('payments', 'Payments'), ('banking', 'Banking'), ('utility', 'Utility'), ('other', 'Other')], db_index=True, max_length=20)),
                ('base_url', models.URLField(blank=True, max_length=500)),
                ('auth_type', models.CharField(choices=[('api_key', 'API Key'), ('bearer', 'Bearer'), ('basic', 'Basic'), ('oauth2', 'OAuth2'), ('custom', 'Custom')], default='api_key', max_length=20)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('secrets_encrypted', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('down', 'Down'), ('sandbox', 'Sandbox')], db_index=True, default='inactive', max_length=20)),
                ('priority', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('supports_webhook', models.BooleanField(default=False)),
                ('webhook_path', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'api_masters',
                'ordering': ['provider_type', '-is_default', 'priority', 'provider_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='apimaster',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('is_deleted', False)), fields=('provider_type',), name='uniq_active_default_per_provider_type'),
        ),
    ]
