# Generated by Django 4.2.7 on 2026-04-22 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillAvenueConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('mode', models.CharField(choices=[('mock', 'Mock'), ('uat', 'UAT'), ('prod', 'Production')], db_index=True, default='mock', max_length=10)),
                ('api_format', models.CharField(choices=[('json', 'JSON'), ('xml', 'XML')], default='json', max_length=10)),
                ('base_url', models.URLField(blank=True, default='', max_length=500)),
                ('access_code', models.CharField(blank=True, default='', max_length=150)),
                ('institute_id', models.CharField(blank=True, default='', max_length=50)),
                ('request_version', models.CharField(blank=True, default='1.0', max_length=10)),
                ('working_key_encrypted', models.TextField(blank=True, default='')),
                ('iv_encrypted', models.TextField(blank=True, default='')),
                ('callback_secret_encrypted', models.TextField(blank=True, default='')),
                ('connect_timeout_seconds', models.PositiveIntegerField(default=30)),
                ('read_timeout_seconds', models.PositiveIntegerField(default=60)),
                ('max_retries', models.PositiveIntegerField(default=2)),
                ('mdm_refresh_hours', models.PositiveIntegerField(default=24)),
                ('mdm_max_calls_per_day', models.PositiveIntegerField(default=15)),
                ('push_callback_url', models.URLField(blank=True, default='', max_length=500)),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billavenue_activated_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billavenue_configs',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BillAvenueAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(default='default', max_length=100)),
                ('agent_id', models.CharField(db_index=True, max_length=40)),
                ('init_channel', models.CharField(choices=[('AGT', 'AGT'), ('INT', 'INT'), ('MOB', 'MOB'), ('INTB', 'INTB'), ('MOBB', 'MOBB'), ('POS', 'POS'), ('ATM', 'ATM'), ('BNKBRNCH', 'BNKBRNCH'), ('BSC', 'BSC'), ('KIOSK', 'KIOSK'), ('MPOS', 'MPOS')], default='AGT', max_length=20)),
                ('require_ip', models.BooleanField(default=True)),
                ('require_mac', models.BooleanField(default=False)),
                ('require_imei', models.BooleanField(default=False)),
                ('require_os', models.BooleanField(default=False)),
                ('require_app', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profiles', to='integrations.billavenueconfig')),
            ],
            options={
                'db_table': 'billavenue_agent_profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillAvenueModeChannelPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('payment_mode', models.CharField(db_index=True, max_length=50)),
                ('payment_channel', models.CharField(db_index=True, max_length=20)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='allow', max_length=10)),
                ('biller_id', models.CharField(blank=True, default='', max_length=20)),
                ('biller_category', models.CharField(blank=True, default='', max_length=100)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mode_channel_policies', to='integrations.billavenueconfig')),
            ],
            options={
                'db_table': 'billavenue_mode_channel_policies',
                'ordering': ['payment_mode', 'payment_channel'],
                'indexes': [models.Index(fields=['payment_mode', 'payment_channel'], name='billavenue__payment_daf8df_idx'), models.Index(fields=['biller_id', 'biller_category'], name='billavenue__biller__9e9676_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='billavenueconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('is_active',), name='uniq_billavenue_active_config'),
        ),
        migrations.AddConstraint(
            model_name='billavenueagentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('config', 'name'), name='uniq_billavenue_agent_profile_name_per_config'),
        ),
    ]
