# Generated by Django 4.2.30 on 2026-08-04 15:00

from django.db import migrations, models


def _dedupe_billavenue_modes(apps, schema_editor):
    """Keep one non-deleted row per uat/prod mode; soft-delete extras."""
    BillAvenueConfig = apps.get_model('integrations', 'BillAvenueConfig')
    for mode in ('uat', 'prod'):
        rows = list(
            BillAvenueConfig.objects.filter(mode=mode, is_deleted=False).order_by(
                '-is_active', '-updated_at', '-id'
            )
        )
        for extra in rows[1:]:
            extra.is_active = False
            extra.is_deleted = True
            extra.save(update_fields=['is_active', 'is_deleted', 'updated_at'])


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_fix_kyc_apimaster_defaults'),
    ]

    operations = [
        migrations.RunPython(_dedupe_billavenue_modes, _noop_reverse),
        migrations.AddConstraint(
            model_name='billavenueconfig',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_deleted', False), ('mode__in', ['uat', 'prod'])),
                fields=('mode',),
                name='uniq_billavenue_mode_uat_prod',
            ),
        ),
    ]
