# Generated by Django 4.2.30 on 2026-09-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0009_dual_env_credentials_and_catalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apimaster",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("kyc", "KYC"),
                    ("payments", "Payments"),
                    ("payout", "Payout"),
                    ("banking", "Banking"),
                    ("utility", "Utility"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
