# Generated by Django 4.2.7 on 2026-04-08 19:31

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_announcement_image_optional_text'),
        ('fund_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadmoney',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='loadmoney',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='loadmoney',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='loadmoney',
            name='fee_breakdown_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='loadmoney',
            name='provider_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='loadmoney',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=191, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='transfer_mode',
            field=models.CharField(choices=[('IMPS', 'IMPS'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS')], db_index=True, default='IMPS', max_length=10),
        ),
        migrations.AlterField(
            model_name='loadmoney',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Gross pay-in amount (principal before deductions).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='loadmoney',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total system deduction (sum of gateway+admin+chain slices on principal).', max_digits=12),
        ),
        migrations.CreateModel(
            name='PayInPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay'), ('payu', 'PayU'), ('mock', 'Mock / Dev')], db_index=True, default='mock', max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12)),
                ('max_amount_per_txn', models.DecimalField(decimal_places=2, default=Decimal('200000'), max_digits=12)),
                ('gateway_fee_pct', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=8)),
                ('admin_pct', models.DecimalField(decimal_places=4, default=Decimal('0.24'), max_digits=8)),
                ('super_distributor_pct', models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=8)),
                ('master_distributor_pct', models.DecimalField(decimal_places=4, default=Decimal('0.02'), max_digits=8)),
                ('distributor_pct', models.DecimalField(decimal_places=4, default=Decimal('0.03'), max_digits=8)),
                ('retailer_commission_pct', models.DecimalField(decimal_places=4, default=Decimal('0.06'), max_digits=8)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('payment_gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_in_packages', to='admin_panel.paymentgateway')),
            ],
            options={
                'db_table': 'pay_in_packages',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='loadmoney',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_money_transactions', to='fund_management.payinpackage'),
        ),
    ]
