# Generated by Django 4.2.27 on 2026-04-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_management', '0004_loadmoney_payment_method_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadmoney',
            name='payment_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Optional details from provider (e.g. card_type, network).'),
        ),
        migrations.AlterField(
            model_name='loadmoney',
            name='payment_method',
            field=models.CharField(blank=True, default='', help_text='Provider channel: upi, card, netbanking, wallet, etc.', max_length=32),
        ),
    ]
