# Generated by Django 4.2.7 on 2026-04-17 04:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_management', '0005_alter_loadmoney_payment_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadmoney',
            name='amount',
            field=models.DecimalField(decimal_places=4, help_text='Gross pay-in amount (principal before deductions).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='loadmoney',
            name='charge',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Total system deduction (sum of gateway+admin+chain slices on principal).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='loadmoney',
            name='net_credit',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='payinpackage',
            name='max_amount_per_txn',
            field=models.DecimalField(decimal_places=4, default=Decimal('200000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='payinpackage',
            name='min_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='payout',
            name='charge',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='payout',
            name='platform_fee',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='payout',
            name='total_deducted',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
    ]
