# Generated by Django 4.2.7 on 2026-04-17 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fund_management', '0006_enterprise_reporting_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='payinpackage',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text='If true, this package is auto-assigned to new users. Only one package can be default.'),
        ),
        migrations.CreateModel(
            name='UserPackageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='The user who assigned this package (Admin or upline).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages_assigned_to_others', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='fund_management.payinpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_package_assignments',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'package')},
            },
        ),
    ]
