# Generated by Django 4.2.27 on 2026-04-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund_management', '0008_payout_slab_tiers'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payoutslabtier',
            new_name='payout_slab_package_5f6782_idx',
            old_name='payout_slab_package_sort_idx',
        ),
    ]
