# Generated by Django 4.2.29 on 2026-05-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund_management', '0010_multi_gateway_payin'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payinpackagegateway',
            new_name='pay_in_pack_package_3d64f3_idx',
            old_name='pay_pkg_gw_pkg_active_idx',
        ),
    ]
