# Generated by Django 4.2.30 on 2026-08-28 08:01

import apps.fund_management.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fund_management", "0013_zero_legacy_retailer_commission"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayInPackageQrLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "pay_in_package_qr_links",
                "ordering": ["package_id", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PayInQrAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("display_name", models.CharField(max_length=200)),
                (
                    "qr_image",
                    models.ImageField(
                        max_length=500,
                        upload_to=apps.fund_management.models.payin_qr_image_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                    ),
                ),
                (
                    "account_display_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("upi_vpa", models.CharField(blank=True, default="", max_length=120)),
                ("bank_details", models.JSONField(blank=True, default=dict)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "daily_limit_24h",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("100000"),
                        help_text="Max gross amount this QR may collect in a rolling 24h window.",
                        max_digits=18,
                    ),
                ),
                (
                    "max_per_txn",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Optional per-transaction cap for this QR.",
                        max_digits=18,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "pay_in_qr_accounts",
                "ordering": ["sort_order", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="PayInQrApprovalAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "action",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "submitted_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("reject_reason", models.TextField(blank=True, default="")),
                ("internal_note", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "pay_in_qr_approval_audits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="loadmoney",
            name="collection_rail",
            field=models.CharField(
                choices=[("gateway", "Gateway"), ("qr", "QR")],
                db_index=True,
                default="gateway",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="loadmoney",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loadmoney",
            name="receipt_image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.fund_management.models.payin_receipt_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="loadmoney",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loadmoney",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_load_money_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loadmoney",
            name="submitted_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Amount user declared at QR submit (before admin approval edit).",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loadmoney",
            name="utr",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="loadmoney",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PENDING_REVIEW", "Pending review"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="loadmoney",
            index=models.Index(
                fields=["collection_rail", "status", "created_at"],
                name="load_money_collect_89f28c_idx",
            ),
        ),
        migrations.AddField(
            model_name="loadmoney",
            name="pay_in_qr_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="load_money_transactions",
                to="fund_management.payinqraccount",
            ),
        ),
        migrations.AddIndex(
            model_name="loadmoney",
            index=models.Index(
                fields=["pay_in_qr_account", "status", "created_at"],
                name="load_money_pay_in__dce5ef_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="loadmoney",
            constraint=models.UniqueConstraint(
                condition=models.Q(("utr__gt", "")),
                fields=("utr",),
                name="load_money_utr_unique_nonempty",
            ),
        ),
        migrations.AddField(
            model_name="payinqrapprovalaudit",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qr_payin_approval_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payinqrapprovalaudit",
            name="load_money",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qr_approval_audits",
                to="fund_management.loadmoney",
            ),
        ),
        migrations.AddIndex(
            model_name="payinqraccount",
            index=models.Index(
                fields=["status", "sort_order"], name="pay_in_qr_a_status_92c765_idx"
            ),
        ),
        migrations.AddField(
            model_name="payinpackageqrlink",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="package_qr_links",
                to="fund_management.payinpackage",
            ),
        ),
        migrations.AddField(
            model_name="payinpackageqrlink",
            name="qr_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="package_links",
                to="fund_management.payinqraccount",
            ),
        ),
        migrations.AddIndex(
            model_name="payinpackageqrlink",
            index=models.Index(
                fields=["package", "is_active", "sort_order"],
                name="pay_in_pack_package_c8bdd3_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payinpackageqrlink",
            unique_together={("package", "qr_account")},
        ),
    ]
