# Generated by Django 4.2.30 on 2026-08-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fund_management", "0015_per_rail_gateway_fees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payinqrapprovalaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("utr_released", "UTR released"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
