# Generated by Django 4.2.30 on 2026-09-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fund_management", "0016_alter_payinqrapprovalaudit_action"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="loadmoney",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["status", "created_at"],
                name="loadmoney_status_created_rpt",
            ),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["status", "created_at"],
                name="payout_status_created_rpt",
            ),
        ),
    ]
