# Generated by Django 4.2.30 on 2026-09-25 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fund_management", "0017_performance_report_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayoutMasterCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("provider_code", models.CharField(db_index=True, max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("banks", "Banks"),
                            ("states", "States"),
                            ("purposes", "Purposes"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("items", models.JSONField(blank=True, default=list)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payout_master_cache",
            },
        ),
        migrations.CreateModel(
            name="PayoutProviderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("provider_code", models.CharField(db_index=True, max_length=80)),
                (
                    "direction",
                    models.CharField(
                        choices=[("outbound", "Outbound"), ("inbound", "Inbound")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("event_type", models.CharField(blank=True, default="", max_length=80)),
                (
                    "merchant_ref_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("http_status", models.PositiveIntegerField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "payout_provider_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="payout",
            name="beneficiary_location",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="payout",
            name="callback_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="merchant_ref_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="provider_charges",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Fee charged by the payout provider (audit only; not our slab).",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="provider_code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=80
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="provider_status_code",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="payout",
            name="provider_txn_id",
            field=models.CharField(blank=True, default="", max_length=191),
        ),
        migrations.AddField(
            model_name="payout",
            name="purpose_code",
            field=models.CharField(blank=True, default="004", max_length=20),
        ),
        migrations.AddField(
            model_name="payout",
            name="request_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="payout",
            name="response_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="payout",
            name="rrn",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(
                fields=["merchant_ref_id"], name="payouts_merchan_9faa15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(
                fields=["provider_code", "status"], name="payouts_provide_e5da52_idx"
            ),
        ),
        migrations.AddField(
            model_name="payoutproviderevent",
            name="payout",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provider_events",
                to="fund_management.payout",
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutmastercache",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("provider_code", "kind"),
                name="uniq_payout_master_provider_kind",
            ),
        ),
        migrations.AddIndex(
            model_name="payoutproviderevent",
            index=models.Index(
                fields=["merchant_ref_id", "created_at"],
                name="payout_prov_merchan_87aceb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payoutproviderevent",
            index=models.Index(
                fields=["provider_code", "direction", "created_at"],
                name="payout_prov_provide_18de8a_idx",
            ),
        ),
    ]
