# Generated by Django 4.2.30 on 2026-10-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fund_management", "0020_platform_payout_slab_deleted_at"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="platformpayoutslabtier",
            new_name="platform_pa_sort_or_5bae0c_idx",
            old_name="platform_pa_sort_or_7d1a2c_idx",
        ),
    ]
