/**
 * @deprecated Import from accessControl.js — re-exports for backward compatibility.
 */
export {
  ACCESS_CODES,
  ACCESS_ERROR_MESSAGES,
  ACCESS_ERROR_TITLES,
  ADMIN_ACCESS_ACTIONS,
  userMayLogin,
  isPayInOnlySession,
  shouldShowPayInOnlyNotice,
  getPayInOnlyRedirectPath,
  canUsePayInModule,
  isPayInModuleOperational,
  isUserRestricted,
  isPaymentsLocked,
  userMayPayIn,
  userMayPayOut,
  isFinancialAppPath,
  isPayInAllowedPath,
  shouldBlockPathForUser,
  messageForAccessCode,
  messageForAccessDetail,
  parseApiAccessError,
  getAccessRedirectMessage,
  getBlockedActionNotice,
  getPageAccessBlockNotice,
  accountAccessBadges,
  getAccessCapabilityRows,
  getEndUserAccessCapabilityRows,
  getUserAccessNoticeVariant,
  formatAdminAccessSuccessMessage,
} from './accessControl';
