# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankVerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider_code', models.CharField(blank=True, default='', max_length=80)),
                ('reference_id', models.CharField(blank=True, default='', max_length=50)),
                ('account_number_last4', models.CharField(blank=True, default='', max_length=4)),
                ('ifsc', models.CharField(blank=True, default='', max_length=11)),
                ('status', models.CharField(blank=True, choices=[('validated', 'Validated'), ('failed', 'Failed'), ('consumed', 'Consumed')], default='', max_length=20)),
                ('validation_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('validation_token_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('request_meta', models.JSONField(blank=True, default=dict)),
                ('response_meta', models.JSONField(blank=True, default=dict)),
                ('wallet_charged', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_verification_attempts', to='authentication.user')),
            ],
            options={
                'db_table': 'bank_verification_attempts',
                'ordering': ['-created_at'],
            },
        ),
    ]
