# Generated by Django 4.2.29 on 2026-06-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_bankverificationattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankverificationattempt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
