# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0004_bankaccount_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='mobile_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
    ]
